### PR TITLE
[WIP] Fix handling of 'ShowHelpOnUnexpected' option

### PR DESCRIPTION
**Pull request by ravenpride**
This PR is a fix for issue #47.

### CODE REVIEW

**Comment by ravenpride** [comment]
Although it works for me, one of your unit tests (TestDoubleParse) fails now.
Could you please have a look at it?

**Comment by ravenpride** [comment]
Ok, the last change should handle trailing arguments better, but the test issue persists. I've debugged it and found out that the test runner itself passes command line arguments to the test application. These arguments do not pass the new validation step. Would it ok for you to add a test specific workaround for this case?

**Comment by ravenpride** [comment]
Ok, that one looks better and all unit test pass. For two unit tests, I had to clear the argument list.
In my opinion, this PR is ready to merge - after your approval, of course :-)

**Comment by ravenpride** [comment]
After playing around with it some more, it seems that the fix works for global flags, but fails for subcommand flags. The issue is trickier than it first looked :-/
Ergo, not ready to merge - but it would be great, if you could share your thoughts with me about this issue. This could help me to fix it.

**Comment by integrii** [comment]
Potentially we could do #55 here instead of this one

**Comment by ravenpride** [comment]
Looks great. I'll close this PR.

**Pull request closed without merging**
